src/CatMyVideo/Models/VideoViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CatMyVideo.Models
{
    public class EditVideoViewModel
    {
        public int Id { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [StringLength(144)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Display(Name = "Tags")]
        [DataType(DataType.Text)]
        public string Tags { get; set; }

        public List<String> _Tags;
    }

    public class CommentViewModel
    {
        [Required]
        [Display(Name = "Content")]
        public string Content;
    }
}

src/CatMyVideo/Controllers/CommentController.cs
using CatMyVideo.Models;
using Storage.Video;
using Storage.WCF;
using Storage.WCF.Contracts;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CatMyVideo.Controllers
{
    [Authorize]
    public class CommentController : Controller
    {
        #region init
        private ApplicationUserManager _userManager;

        public CommentController()
        {
        }

        public CommentController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_userManager != null)
                {
                    _userManager.Dispose();
                    _userManager = null;
                }
            }

            base.Dispose(disposing);
        }
        #endregion

        [Route("/Comment/Create/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int id, String content)
        {
            var video = Engine.BusinessManagement.Video.GetVideo(id);
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (video == null)
            {
                ViewBag.InvalidComment = true;
                return RedirectToAction("Display", "Video", new
                {
                    id = id,
                });
            }

            Engine.BusinessManagement.Comment.AddComment(new Engine.Dbo.Comment()
            {
                Message = content,
                Video = id,
                PostDate = DateTime.Now,
                User = Engine.BusinessManagement.User.FindUser(user.T_UserId),
            });
            return RedirectToAction("Display", "Video", new { id = id });
        }

        [Route("/Comment/Delete/{id}")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var comment = Engine.BusinessManagement.Comment.GetComment(id);
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (comment.User.Nickname == user.UserName || User.IsInRole("Admin,Moderator"))
            {
                Engine.BusinessManagement.Comment.DeleteComment(comment);
                return RedirectToAction("Display", "Video", new { id = comment.Video });
            }
            return RedirectToAction("Display", "Video", new { id = comment.Video, errorDeletedComment = true });
        }

        [Route("/Comment/Update/{id}")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Update(int id, int videoid, String content)
        {
            var comment = Engine.BusinessManagement.Comment.GetComment(id);
            var user = UserManager.FindById(User.Identity.GetUserId());
            if (comment.Video == videoid && (comment.User.Nickname == user.UserName || User.IsInRole("Admin,Moderator")))
            {
                comment.Message = content;
                Engine.BusinessManagement.Comment.UpdateComment(comment);
            }
            return RedirectToAction("Display", "Video", new { id = comment.Video });
        }
    }
}

src/CatMyVideo/Controllers/VideoController.cs
using CatMyVideo.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Linq;

namespace CatMyVideo.Controllers
{
    public class VideoController : Controller
    {
        #region init
        private ApplicationUserManager _userManager;

        public VideoController()
        {
        }

        public VideoController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get { return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>(); }
            private set { _userManager = value; }
        }
        #endregion

        [Route("/Video/Display/{id}")]
        public ActionResult Display(int id = 1, bool? updated = false, bool? errorDeleted = false, bool? errorDeletedComment = false)
        {
            var video = Engine.BusinessManagement.Video.GetVideo(id, true);
            if (video == null)
                return RedirectToAction("Index", "Home");

            var user = video.User;
            ViewBag.Username = user.Nickname;
            ViewData["tags"] = Engine.BusinessManagement.Tag.ListTagsByVideoId(video.Id);
            ViewData["comments"] = Engine.BusinessManagement.Comment.ListCommentByVideoId(video.Id, 20, 0);
            ViewData["numberComments"] = Engine.BusinessManagement.Comment.CountCommentsByVideoId(video.Id);

            if (video.Encodes.Count == 0)
                return View("Error", video);

            ApplicationUser connectedUser = null;
            if (User.Identity.IsAuthenticated)
                connectedUser = UserManager.FindById(User.Identity.GetUserId());

            ViewBag.CanDelete = connectedUser != null && user.Nickname == connectedUser.UserName || User.IsInRole("Admin") || User.IsInRole("Moderator");
            ViewBag.CanEdit = connectedUser != null && (user.Nickname == connectedUser.UserName || User.IsInRole("Admin") || User.IsInRole("Moderator"));

            Engine.BusinessManagement.Video.IncrementViewCount(video.Id);

            ViewBag.Updated = updated;
            ViewBag.ErrorDeleted = errorDeleted;
            ViewBag.ErrorDeletedComment = errorDeletedComment;

            return View("Index", video);
        }

        [Route("/Video/Edit/{id}")]
        public ActionResult Edit(int id)
        {
            Engine.Dbo.Video video = Engine.BusinessManagement.Video.GetVideo(id);

            if (video == null)
                return RedirectToAction("Index", "Home");

            // TODO: check user rights

            EditVideoViewModel model = new EditVideoViewModel() {
              Id = video.Id,
              Title = video.Title,
              Description = video.Description,
            };

            var tags = Engine.BusinessManagement.Tag.ListTagsByVideoId(video.Id).Select(x => x.Name).ToArray();
            model.Tags = String.Join(" ", tags);

            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(EditVideoViewModel model)
        {
            if (!model.Tags.Split(' ').All(x => x.Length <= 20))
                ModelState.AddModelError("Tags", "Tags must be 20 charaters long and contains only number, letter and -");
            if (ModelState.IsValid)
            {
                var oldVideo = Engine.BusinessManagement.Video.GetVideo(model.Id);
                Engine.BusinessManagement.Video.UpdateVideo(new Engine.Dbo.Video()
                    {
                        Id = model.Id,
                        UploadDate = oldVideo.UploadDate,
                        ViewCountToday = oldVideo.ViewCountToday,
                        ViewCountTotal = oldVideo.ViewCountTotal,
                        Title = model.Title,
                        Description = model.Description,
                        User = oldVideo.User,
                        Encodes = oldVideo.Encodes,
                        Comments = oldVideo.Comments,
                    });
                Engine.BusinessManagement.Tag.AddTags(model.Tags.Split().Distinct().Select(x => new Engine.Dbo.Tag() { Name = x }), model.Id);

                return RedirectToAction("Display", "Video", new { id = model.Id, updated = true });    
            }
            return View("Edit", model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());
            var video = Engine.BusinessManagement.Video.GetVideo(id);
            if (video != null && (video.User.AspNetUsersId == user.Id || User.IsInRole("Admin") || User.IsInRole("Moderator")))
            {
                try
                {
                    var driver = new Storage.MongoFS.Driver();
                    IList<Engine.Dbo.Encode> encodes = Engine.BusinessManagement.Encode.ListEncode(id, true);
                    foreach (Engine.Dbo.Encode encode in encodes)
                    {
                        Engine.BusinessManagement.Encode.DeleteEncode(encode);
                    }
                    Engine.BusinessManagement.Video.DeleteVideo(id);
                    driver.DeleteStreamAndThumb(Convert.ToString(id), encodes);
                    return RedirectToAction("Display", "Account", new { nickname = user.UserName });
                }
                catch (Exception)
                { }
            }
            return RedirectToAction("Display", "Video", new { id = id, errorDeleted = true });
        }
    }
}

src/CatMyVideo/Views/Video/Edit.cshtml
@using CatMyVideo.Models
@model EditVideoViewModel

@{
  ViewBag.Title = "Edit video";
}

<h2>Edit video</h2>

<div class="row">
  <div class="medium-8 medium-centered large-5 columns">
    @using (Html.BeginForm("Update", "Video", FormMethod.Post, new { role = "form" }))
    {
      @Html.AntiForgeryToken()
      @Html.ValidationSummary("", new { @class = "error" })
      @Html.TextBoxFor(m => m.Id, new { type = "hidden"})
      <label>
        @Html.LabelFor(m => m.Title)
        @Html.TextBoxFor(m => m.Title)
        @Html.ValidationMessageFor(m => m.Title, "", new { @class = "danger" })
      </label>
      <label>
        @Html.LabelFor(m => m.Description)
        @Html.TextAreaFor(m => m.Description)
        @Html.ValidationMessageFor(m => m.Description, "", new { @class = "danger" })
      </label>
      <label>
        @Html.LabelFor(m => m.Tags) (separated with whitespaces)
        @Html.TextBoxFor(m => m.Tags)
        @Html.ValidationMessageFor(m => m.Tags, "", new { @class = "danger" })
      </label>
      <input type="submit" value="Save changes" class="button primary expand" />
    }
  </div>
</div>

src/CatMyVideo/Views/Video/Index.cshtml
@model Engine.Dbo.Video
@{
    ViewBag.Title = "Index";
    var tags = ViewData["tags"] as List<Engine.Dbo.Tag>;
    var comments = ViewData["comments"] as List<Engine.Dbo.Comment>;

    List<Engine.Dbo.Encode> EncodesList = Model.Encodes.Where(x => !x.IsBase).OrderBy(x => x.Quality).ToList();
}

@if (ViewBag.Updated != null && ViewBag.Updated)
{
    <div data-alert class="alert-box success">
        This video has been updated.
        <a href="#" class="close">&times;</a>
    </div>
}

@if (ViewBag.ErrorDeleted != null && ViewBag.ErrorDeleted)
{
    <div data-alert class="alert-box error">
        This video was not deleted.
        <a href="#" class="close">&times;</a>
    </div>
}

@if (ViewBag.ErrorDeletedComment != null && ViewBag.ErrorDeletedComment)
{
    <div data-alert class="alert-box error">
        This comment was not deleted.
        <a href="#" class="close">&times;</a>
    </div>
}

<div class="row">
    <div class="small-8 columns">
        <h2>
            @Model.Title
            <small>
                By <a href="@Url.Action("Display", "Account", new { nickname = ViewBag.Username })">@ViewBag.Username</a>
                - @Model.ViewCountTotal views
            </small>
        </h2>
    </div>
    <div class="small-4 columns text-right">
        <h2>
            <a href="#"><i class="fi-social-facebook"></i></a>
            <a href="#"><i class="fi-social-google-plus"></i></a>
        </h2>
    </div>
</div>

<div class="row">
    @if (ViewBag.CanDelete != null && ViewBag.CanEdit != null && (ViewBag.CanEdit || ViewBag.CanDelete))
    {
        <div class="medium-1 columns">
            <h2>
                @if (ViewBag.CanDelete != null && ViewBag.CanDelete)
                {
                    <a href="" data-reveal-id="trash-video-@Model.Id"><i class="fi-trash"></i></a>
                }
                @if (ViewBag.CanEdit != null && ViewBag.CanEdit)
                {
                    <a href="@Url.Action("Edit", "Video", new { id = Model.Id })"><i class="fi-pencil"></i></a>
                }
            </h2>
        </div>
    }
    <div class="medium-10 medium-centered columns">
        <video id="video" class="video-js vjs-default-skin" controls
               preload="auto" width="auto" height="auto"
               poster="@Url.Action("GetImage", "api/VideoAPI", new { id = @Model.Id })"
               data-setup='{ "plugins" : { "resolutionSelector" : { "default_res" : "480" } } }'>
            @foreach (var encode in EncodesList)
            {
                var quality = encode.Quality.ToString();
                <source data-res="@quality.Substring(1)" src="/api/VideoApi/Get/@encode.Id" type='video/mp4'>
            }
            <p class="vjs-no-js">To view this video please enable JavaScript, and consider upgrading to a web browser that <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a></p>
        </video>
    </div>
</div>

<div class="row">
    <div class="medium-10 medium-centered columns text-center">
        @foreach (var tag in tags)
        {
            <span class="label info">#@tag.Name</span>
        }
    </div>
</div>
<hr />
<div class="row">
    <div class="medium-10 medium-centered columns">
        <small>@Model.UploadDate.ToString("dd/MM/yyyy")</small>
        <p>@Model.Description</p>
    </div>
</div>
<hr />
<div class="row">
    <div class="medium-3 medium-centered columns text-center">
        <button data-dropdown="drop" aria-controls="drop" aria-expanded="false" class="large alert button dropdown">Download</button><br>
        <ul id="drop" data-dropdown-content class="f-dropdown" role="menu" aria-hidden="false" tabindex="-1">
            @foreach (var encode in Model.Encodes)
            {
                switch (encode.Quality)
                {
                    case Engine.Dbo.Encode.Definition.p480:
                        <li><a href="@Url.Action("Get", "api/VideoAPI", new { id = encode.Id })" download="@Html.AttributeEncode(Model.Title + "_480p.mp4")">480p</a></li>
                        break;
                    case Engine.Dbo.Encode.Definition.p720:
                    <li><a href="@Url.Action("Get", "api/VideoAPI", new { id = encode.Id })" download="@Html.AttributeEncode(Model.Title + "_720p.mp4")">720p</a></li>
                        break;
                    case Engine.Dbo.Encode.Definition.p1080:
                    <li><a href="@Url.Action("Get", "api/VideoAPI", new { id = encode.Id })" download="@Html.AttributeEncode(Model.Title + "_1080p.mp4")">1080p</a></li>
                        break;
                    case Engine.Dbo.Encode.Definition.None:
                    default:
                        break;
                }
            }
        </ul>
    </div>
</div>
<hr />
<h3>Comments (@ViewData["numberComments"])</h3>

<div class="row">
    <div class="medium-10 medium-centered columns">
        @using (Html.BeginForm("Create", "Comment", FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            <label>
                @Html.TextArea("Content")
                @Html.TextBox("id", Model.Id, new { type = "hidden" })
            </label>
            <input type="submit" value="Post comment" class="button primary expand" />
        }

        <div id="comment-display">
            @foreach (var comment in comments)
            {
                <div class="row" id="comment_@comment.Id">
                    @if ((ViewBag.CanDelete != null && ViewBag.CanDelete) || comment.User.Nickname == User.Identity.Name)
                    {
                        <div>
                            <a href="" onclick="change_modal_delete_comment(@Html.AttributeEncode(comment.Id))" data-reveal-id="trash-comment"><i class="fi-trash"></i></a>
                            <a href="" onclick="change_modal_update_comment(@Html.AttributeEncode(comment.Id))" data-reveal-id="update-comment"><i class="fi-pencil"></i></a>
                        </div>
                    }
                    <div class="medium-10 columns medium-centered">
                        <p id="comment-content-@Html.AttributeEncode(comment.Id)">@comment.Message</p>
                    </div>
                    <div class="row">
                        <div class="medium-10 medium-centered columns text-right">
                            By <a href="@Url.Action("Display", "Account", new { id = comment.User.Id } )">@comment.User.Nickname</a>, posted on <em>@comment.PostDate.ToString("dd/MM/yyyy") at @comment.PostDate.ToString("HH:mm")</em>
                        </div>
                    </div>
                    <hr />
                </div>
            }
        </div>
        @if (comments.Count < Convert.ToInt32(ViewData["numberComments"]))
        {
            <a href="#load-more-comment" onclick="load_more_comment(this)" videoid="@Html.AttributeEncode(Model.Id)" max="@Html.AttributeEncode(@ViewData["numberComments"])" loaded="@Html.AttributeEncode(comments.Count)" id="load-more-comment" class="button success">Load more</a>
        }
    </div>
</div>

<div id="trash-video-@Model.Id" class="reveal-modal small" data-reveal aria-labelledby="Delete this video?" aria-hidden="true" role="dialog">
    <h2 id="modalTitle">Delete "@Model.Title"?</h2>
    <p class="lead">Do you really want to delete this video?</p>
    <p>
        Be careful! This action cannot be undone.
    </p>
    <p class="text-right">
        @using (Html.BeginForm("Delete", "Video", new { id = Model.Id }, FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            <input type="submit" value="Delete it!" class="button tiny alert" aria-label="Close" />
        }
    </p>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div id="trash-comment" class="reveal-modal small" data-reveal aria-labelledby="Delete this comment?" aria-hidden="true" role="dialog">
    <h2 id="modalTitle">Delete the comment?</h2>
    <p class="lead">Do you really want to delete this comment?</p>
    <p>
        Be careful! This action cannot be undone.
    </p>
    <p class="text-right">
        @using (Html.BeginForm("Delete", "Comment", new { id = 1 }, FormMethod.Post, new { id = "delete-comment", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <input type="submit" value="Delete it!" class="button tiny alert" aria-label="Close" />
        }
    </p>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>


<div id="update-comment" class="reveal-modal small" data-reveal aria-labelledby="Update this comment?" aria-hidden="true" role="dialog">
    <h2 id="modalTitle">Update the comment?</h2>
    <p class="lead">Do you really want to update this comment?</p>
    <p class="text-right">
        @using (Html.BeginForm("Update", "Comment", new { id = 1 }, FormMethod.Post, new { id = "change-comment", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <label>
                @Html.TextArea("Content", new { id = "update-comment-content" })
                @Html.TextBox("videoid", Model.Id, new { type = "hidden" })
            </label>
            <input type="submit" value="Update this comment" class="button tiny alert" aria-label="Close" />
        }
    </p>
    <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>